spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/imagelite
    username: admin
    password: password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true